// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2CMESAAd0e-UzfyaOBGUI-6y-iRPT25w',
    appId: '1:797253797965:web:8c7bf8781e87bc0a04f404',
    messagingSenderId: '797253797965',
    projectId: 'e-commerce-app-e55e6',
    authDomain: 'e-commerce-app-e55e6.firebaseapp.com',
    storageBucket: 'e-commerce-app-e55e6.appspot.com',
    measurementId: 'G-45201C3W8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIpSBp6PBWf0a6no5tP2ufcOVqlAoMfro',
    appId: '1:797253797965:android:09707efee61c318804f404',
    messagingSenderId: '797253797965',
    projectId: 'e-commerce-app-e55e6',
    storageBucket: 'e-commerce-app-e55e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cevbjVLXcO-0ig60-TjdRrmqIbfISnA',
    appId: '1:797253797965:ios:8376f1a02c0fb20f04f404',
    messagingSenderId: '797253797965',
    projectId: 'e-commerce-app-e55e6',
    storageBucket: 'e-commerce-app-e55e6.appspot.com',
    iosClientId:
        '797253797965-2fealoa4nlp3fof4qtf0fehn3s7st2ne.apps.googleusercontent.com',
    iosBundleId: 'com.eCommerceAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cevbjVLXcO-0ig60-TjdRrmqIbfISnA',
    appId: '1:797253797965:ios:8376f1a02c0fb20f04f404',
    messagingSenderId: '797253797965',
    projectId: 'e-commerce-app-e55e6',
    storageBucket: 'e-commerce-app-e55e6.appspot.com',
    iosClientId:
        '797253797965-2fealoa4nlp3fof4qtf0fehn3s7st2ne.apps.googleusercontent.com',
    iosBundleId: 'com.eCommerceAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2CMESAAd0e-UzfyaOBGUI-6y-iRPT25w',
    appId: '1:797253797965:web:7a75ca2bb673506e04f404',
    messagingSenderId: '797253797965',
    projectId: 'e-commerce-app-e55e6',
    authDomain: 'e-commerce-app-e55e6.firebaseapp.com',
    storageBucket: 'e-commerce-app-e55e6.appspot.com',
    measurementId: 'G-2HE0Q0WSKF',
  );
}
